# Generated by Django 4.2.7 on 2025-09-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
